### ISSUE TITLE
Cannot build with react native 0.47.1

### ISSUE THREAD

**Issue by fwal** [acaziasoftcom/react-native-bottomsheet#4]
Cannot build with react native `0.47.1` and react-native-bottomsheet `1.5.0`:
```
../node_modules/react-native-bottomsheet/android/src/main/java/com/clipsub/rnbottomsheet/RNBottomSheetPackage.java:28: error: method does not override or implement a method from a supertype
```

**Comment by fwal** [comment]
~Never mind, I think my yarn failed to upgrade properly 😞~

**Comment by fwal** [comment]
Oh, the fix isn't released yet... Any eta?

**Comment by Doko-Demo-Doa** [comment]
Sorry it's fixed now. Please update the package from npm.

**Comment by kholiavko-roman** [comment]
It works on reat-native `0.47.1`, but now works on react-native `0.46.4`

Error output:
```
:react-native-bottomsheet:generateReleaseSources
:react-native-bottomsheet:incrementalReleaseJavaCompilationSafeguard
:react-native-bottomsheet:compileReleaseJavaWithJavac
:react-native-bottomsheet:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/roman/Projects/test-chat /node_modules/react-native-bottomsheet/android/src/main/java/com/clipsub/rnbottomsheet/RNBottomSheetPackage.java:15: error: RNBottomSheetPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNBottomSheetPackage implements ReactPackage {
       ^
1 error
:react-native-bottomsheet:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-bottomsheet:compileReleaseJavaWithJavac
```

**Comment by Doko-Demo-Doa** [comment]
@kholiavko-roman Please use v1.5.0, I will make a new version with backward-compatible this weekend.

**Comment by kholiavko-roman** [comment]
Yes, I already use previous version. Thanks you for replay. Will be waiting.

**Comment by Doko-Demo-Doa** [comment]
Hello @fwal @kholiavko-roman I just published a new version on both Github and NPM. It should works on RN 0.47 as well as earlier version now (easier than I thought, simply remove `@Override` annotation on the native side).

Note: If you still have problems on older version, please revert back to 1.5.0.

**Comment by Doko-Demo-Doa** [comment]
As a side note, I also fixed `https://github.com/Clip-sub/react-native-shake` to be used with RN 0.47 and earlier versions.

**Comment by escapar** [comment]
it seems to me that this issue is occurring now in react-native 0.62 in version 1.5.0, 1.8.1 and 2.0.1.

RNBottomSheetPackage.java:14: error: RNBottomSheetPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNBottomSheetPackage implements ReactPackage {
}


update:  this is not a library problem. fixed using this approach https://github.com/facebook/react-native/issues/21981#issuecomment-516880662
